global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order:7172']
  - job_name: 'inventory'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory:7171']